import "./globals.css";
import localFont from "next/font/local";

const pressStart = localFont({
  src: "./fonts/press-start-2p-latin-400-normal.woff2",
  variable: "--font-press-start",
  display: "block",
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pressStart.className} ${pressStart.variable} mosaic-font`}>{children}</body>
    </html>
  );
}
